# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-02 22:57
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180402_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
    ]
